import type { ChaosProfile } from '../types/synth'

export const chaosProfiles: Record<string, ChaosProfile> = {
  LOVE: {
    name: 'LOVE',
    color: '#ff9326',
    description: 'Sanft & Musikalisch',
    noise: { min: 0, max: 5 },
    distortion: { min: 0, max: 8 },
    filterRes: { min: 1.5, max: 8 },
    filterFreq: { min: 400, max: 8000 },
    feedback: { min: 0, max: 0.45 },
    attack: { min: 5, max: 200 },
    oscMixer: { min: -25, max: 25 },
    volume: { min: 30, max: 110 },
    waveform: 'smooth',
    reverbSend: { min: 20, max: 95 },
    delaySend: { min: 5, max: 60 },
  },
  HATE: {
    name: 'HATE',
    color: '#ffaa00',
    description: 'Aggressiv & 303-Style',
    noise: { min: 0, max: 20 },
    distortion: { min: 0, max: 20 },
    filterRes: { min: 1, max: 12 },
    filterFreq: { min: 500, max: 10000 },
    feedback: { min: 0, max: 0.6 },
    attack: { min: 1, max: 50 },
    oscMixer: { min: -30, max: 30 },
    volume: { min: 40, max: 100 },
    waveform: 'mixed',
    reverbSend: { min: 0, max: 80 },
    delaySend: { min: 0, max: 80 },
  },
  SABOTAGE: {
    name: 'SABOTAGE',
    color: '#ff0000',
    description: 'TOTALES CHAOS!!!',
    noise: { min: 0, max: 127 },
    distortion: { min: 0, max: 127 },
    filterRes: { min: 0.1, max: 30 },
    filterFreq: { min: 50, max: 20000 },
    feedback: { min: 0, max: 0.95 },
    attack: { min: 0, max: 500 },
    oscMixer: { min: -63, max: 63 },
    volume: { min: 0, max: 127 },
    waveform: 'chaos',
    reverbSend: { min: 0, max: 127 },
    delaySend: { min: 0, max: 127 },
  },
}
